### PR TITLE
feat: replace license key encryption

### PR DESCRIPTION
**Pull request by asbiin**
The current """encryption""" consist in adding a private key to the jsoned license key, and encode it as base64. This actually is not *encrypting* anything at all.

I propose to replace that using the laravel `Encrypter` which is using a `AES-256-CBC` encryption method.
The private key must be shared with Monica and OfficeLife, so they can decrypt it.

### CODE REVIEW

**Comment by djaiss** [comment]
> The current """encryption""" consist in adding a private key to the jsoned license key, and encode it as base64. This actually is not _encrypting_ anything at all.

ahah i know. it was just a way for me to add a bit of security, just to not make it too easy to crack the system.

**Review by djaiss — APPROVED** [review]
Good job!!

**Comment by djaiss** [comment]
@asbiin how would the client call the service in this case?

**Comment by djaiss** [comment]
Also, we need to update the [app/Services/Account/Subscription/ActivateLicenceKey.php](https://github.com/monicahq/monica/pull/6049/files/0ddd47bae6e1bf936f6e00ba8b84b2c2c1f26d26#diff-a8a4929d23051fe5d266ecedd5152d66ca76c55a4ab3112c7798ec105df37bca) function for this to work too.

**Comment by asbiin** [comment]
> @asbiin how would the client call the service in this case?

@djaiss There is an example in the passport documentation https://laravel.com/docs/9.x/passport#retrieving-tokens
You'll need to make 2 calls:
- 1 to get an access_token
- 1 to call the api using the access_token as auth (bearer) token

**Pull request merged**
